# Generated by Django 2.2.5 on 2021-02-24 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Techblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.TextField(default='')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('date', models.DateField()),
                ('directory', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='techalook.Techblog')),
            ],
        ),
    ]
