# Generated by Django 2.2.5 on 2021-02-24 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techalook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='directory',
        ),
        migrations.AddField(
            model_name='card',
            name='Directory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='techalook.Techblog'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
