# Generated by Django 2.2.5 on 2021-02-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techalook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='Directory',
            new_name='directory',
        ),
    ]
